[project]
name = "langchainplayground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.10.0",
    "isort>=9.0.2",
    "langchain>=1.4.3",
    "langchain-google-genai>=4.4.0",
    "langchain-ollama>=1.1.0",
    "python-dotenv>=1.2.4",
]
